---
abstract: 'Retrieve random lines from a file'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Spec: 0
  File::Spec::Functions: 0
  File::Temp: 0
  List::Util: 0
  Test::Exception: 0
  Test::MockRandom: 0
  Test::More: 0
  Test::Warn: 0
  blib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-RandomLine
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  File::RandomLine:
    file: lib/File/RandomLine.pm
    version: 0.20
requires:
  Carp: 0
  Want: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/dagolden/file-randomline/issues
  homepage: https://metacpan.org/release/File-RandomLine
  repository: git://github.com/dagolden/file-randomline.git
version: 0.20
